from datetime import datetime, timedelta

from analyzer.services.baseline import build_baseline_for_customer

LARGE_TRANSACTION_MULTIPLIERS = {"medium": 1.5, "high": 3.0}

NEW_PAYEE_BURST_MIN_COUNT = 3
NEW_PAYEE_BURST_MAX_WINDOW_DAYS = 3
NEW_PAYEE_RECENT_THRESHOLD_DAYS = 7  # payee must have first appeared this recently

BEHAVIORAL_BREAK_WINDOW_DAYS = 7
BEHAVIORAL_BREAK_AMOUNT_MULTIPLIER = 1.5
BEHAVIORAL_BREAK_CHANNEL_CONCENTRATION = 0.7
BEHAVIORAL_BREAK_PAYEE_UNFAMILIAR_RATIO = 0.5
BEHAVIORAL_BREAK_FREQUENCY_MULTIPLIER = 2.0
BEHAVIORAL_BREAK_MIN_DIMENSIONS = 2

ACTIVITY_BURST_WINDOW_DAYS = 3
ACTIVITY_BURST_MULTIPLIER = 3.0
ACTIVITY_BURST_MIN_COUNT = 4
